

### Listar disciplinas
GET https://localhost:5001/api/disciplina/listar

### Listar disciplinas por aluno
//GET https://localhost:5001/api/disciplina/buscar/2



### Cadastrar disciplina [ disciplina só é cadastrada  
###  se tiver um professor com cpf ja cadastrado no banco ] 
POST https://localhost:5001/api/disciplina/cadastrar
Content-Type: application/json

{
    "Nome": "Matemática",
    "CpfProfessor": "88888888"
    
}

### Atualizar disciplina
PATCH https://localhost:5001/api/disciplina/alterar
Content-Type: application/json

{
    "id" : 5,
    "nome": "Portugues",
    "CpfProfessor": "88888888"
    
}

### Deletar disciplina
DELETE https://localhost:5001/api/disciplina/deletar/1



### LIMPAR TODAS AS TABELAS EXISTENTES NO BANCO
DELETE https://localhost:5001/api/disciplina/deletarall



