### Listar professores
GET https://localhost:5001/api/professor/listar

### Cadastrar professor
POST https://localhost:5001/api/professor/cadastrar
Content-Type: application/json

{
    "Nome" : "maRIA",
    "Cpf" : "88888888",
    "Email" : "abc@.com",
    "Telefone" : "12345678333"
    
    
}

### Buscar um professor pelo CPF
GET https://localhost:5001/api/professor/buscar/12345678999

### Deletar um professor pelo Id
DELETE https://localhost:5001/api/professor/deletar/36

### Alterar um professor
PATCH  https://localhost:5001/api/professor/alterar
Content-Type: application/json

{
    "id" : 35,
    "nome" : "nomeAlterado",
    "cpf" : "12345678999"
}