### Listar os alunos
GET https://localhost:5001/api/aluno/listar

### Cadastrar um aluno
POST https://localhost:5001/api/aluno/cadastrar
Content-Type: application/json

{
    "nome" : "Teste",
    "cpf" : "12312312312",
    "email" : "email@teste",
    "telefone": "123456789",
    "rgm" : "1000",
    "nascimento" : "1900-09-20"
}

### Buscar um aluno pelo CPF
GET https://localhost:5001/api/aluno/buscar/12312312312

### Deletar um aluno pelo Id
DELETE https://localhost:5001/api/aluno/deletar/3

### Alterar um aluno
PATCH  https://localhost:5001/api/aluno/alterar
Content-Type: application/json

{
    "id" : 1,
    "nome" : "NomeAlteradoTeste",
    "cpf" : "12345678911"
}