### Cadastrar um Boletim
POST https://localhost:5001/api/boletim/cadastrar
Content-Type: application/json

{
    "CodigoTurma" : 12,
    "AlunoCpf" : "12312312312"
}

### Listar os Boletins
GET https://localhost:5001/api/boletim/listar

### Listar boletins por codigo da turma
GET https://localhost:5001/api/boletim/buscar/12

### Buscar um boletim pelo id
GET https://localhost:5001/api/boletim/buscar-id/1

### Deletar um boletim pelo Id
DELETE https://localhost:5001/api/boletim/deletar/1

### Alterar um boletim
PATCH  https://localhost:5001/api/boletim/alterar
Content-Type: application/json

{
    "id" : 1,
    "AlunoCpf" : "12312312312",
    "status" : "Aprovado"
}